services:
  db:
    image: mysql:8.0
    container_name: inventory_sales_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory_sales
    ports:
      - "3307:3306"
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: .
    container_name: inventory_sales_api
    environment:
      DB_URL: jdbc:mysql://db:3306/inventory_sales?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      DB_USERNAME: root
      DB_PASSWORD: root
      JWT_SECRET: 8vN$3kL!pQ9zX2mR#7sT@4wY6bH1cD5fJ8nK!2pL
      JWT_EXP_MINUTES: 120
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data: