services:
  db:
    image: mysql:8.0
    container_name: inventory_sales_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory_sales
    ports:
      - "3306:3306"
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: .
    container_name: inventory_sales_api
    environment:
      DB_URL: jdbc:mysql://db:3306/inventory_sales?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      DB_USERNAME: root
      DB_PASSWORD: root
      JWT_SECRET: CHANGE_ME_TO_A_LONG_RANDOM_SECRET_KEY_32+_CHARS
      JWT_EXP_MINUTES: 120
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data: