spring.application.name=inventory-sales-api
server.port=8080

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/inventory_sales?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

jwt.secret=${JWT_SECRET:CHANGE_ME_TO_A_LONG_RANDOM_SECRET_KEY_32+_CHARS}
jwt.expiration-minutes=${JWT_EXP_MINUTES:120}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

management.endpoints.web.exposure.include=health,info